[package]
name = "gb_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gb"
path = "src/main.rs"

[dependencies]
thiserror = "1.0.50"

[workspace]
resolver = "2"
members = ["gbc_lex" 
]
